// Code generated by protoc-gen-go.
// source: riemann.proto
// DO NOT EDIT!

/*
Package riemannpb is a generated protocol buffer package.

It is generated from these files:
	riemann.proto

It has these top-level messages:
	State
	Event
	Query
	Msg
	Attribute
*/
package riemannpb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type State struct {
	Time        int64    `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	State       string   `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Service     string   `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
	Host        string   `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	Description string   `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Once        bool     `protobuf:"varint,6,opt,name=once" json:"once,omitempty"`
	Tags        []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Ttl         float32  `protobuf:"fixed32,8,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}

type Event struct {
	Time         int64        `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	State        string       `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Service      string       `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
	Host         string       `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	Description  string       `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Tags         []string     `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Ttl          float32      `protobuf:"fixed32,8,opt,name=ttl" json:"ttl,omitempty"`
	Attributes   []*Attribute `protobuf:"bytes,9,rep,name=attributes" json:"attributes,omitempty"`
	TimeMicros   int64        `protobuf:"varint,10,opt,name=time_micros" json:"time_micros,omitempty"`
	MetricSint64 int64        `protobuf:"zigzag64,13,opt,name=metric_sint64" json:"metric_sint64,omitempty"`
	MetricD      float64      `protobuf:"fixed64,14,opt,name=metric_d" json:"metric_d,omitempty"`
	MetricF      float32      `protobuf:"fixed32,15,opt,name=metric_f" json:"metric_f,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Query struct {
	String_ string `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}

type Msg struct {
	Ok     bool     `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
	Error  string   `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	States []*State `protobuf:"bytes,4,rep,name=states" json:"states,omitempty"`
	Query  *Query   `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	Events []*Event `protobuf:"bytes,6,rep,name=events" json:"events,omitempty"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}

func (m *Msg) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *Msg) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Msg) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Attribute struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}

func init() {
}
